# Add 'frontend' label to any change within the 'components' or 'src' directory
frontend:
  - components/**/*
  - src/**/*

# Add 'backend' label to any change within the 'services' directory
backend:
  - services/**/*

# Add 'documentation' label to any change to .md files
documentation:
  - "**/*.md"
